//! Compiles the `.bpf.c` programs in `src/bpf/` to BPF object files.
//!
//! Requirements, both host prerequisites — neither is installed or
//! generated automatically, since faking either would silently produce
//! wrong output rather than a clear failure:
//!
//! 1. `clang` with a `bpf` target (any reasonably recent clang; BPF codegen
//!    has been upstream for years). Checked via `clang --print-targets`.
//! 2. `src/bpf/vmlinux.h` — the target kernel's BTF-derived type
//!    definitions, generated with:
//!    `bpftool btf dump file /sys/kernel/btf/vmlinux format c > src/bpf/vmlinux.h`
//!    This is deliberately NOT checked into the repo and NOT generated by
//!    this script: it must match the kernel BPF CO-RE relocations are
//!    computed against, and a hand-written or stale approximation would
//!    silently produce wrong struct-field offsets — exactly the kind of
//!    "looks like it works, provides no real guarantee" failure this
//!    codebase's own review process flagged elsewhere. Generate it fresh
//!    against whatever kernel will actually run these programs (a CI job
//!    does this against the runner's own kernel — see .github/workflows).
//!
//! If either prerequisite is missing, this script does NOT fail the
//! build — other crates in the workspace must stay buildable without a
//! full BPF toolchain (e.g. iterating on aivisor-runtime alone). Instead
//! it prints a `cargo:warning` and leaves `AIVISOR_BPF_OUT_DIR` unset, so
//! `aivisor_bpf::loader::BpfLoader::load_and_attach()` fails loudly and
//! specifically at the point something actually tries to use it, rather
//! than this crate silently compiling with no BPF programs behind it.

use std::env;
use std::path::{Path, PathBuf};
use std::process::Command;

const OBJECTS: &[&str] = &["fs", "exec", "net", "priv", "task"];

fn main() {
    let bpf_src_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/bpf");
    let vmlinux_h = bpf_src_dir.join("vmlinux.h");

    for name in OBJECTS {
        println!(
            "cargo:rerun-if-changed={}",
            bpf_src_dir.join(format!("{name}.bpf.c")).display()
        );
    }
    println!(
        "cargo:rerun-if-changed={}",
        bpf_src_dir.join("common.h").display()
    );
    println!("cargo:rerun-if-changed={}", vmlinux_h.display());

    let clang = match find_clang() {
        Some(c) => c,
        None => {
            println!(
                "cargo:warning=aivisor-bpf: clang not found — BPF programs will not be built. \
                 aivisor_bpf::loader::BpfLoader::load_and_attach() will return a clear error at \
                 runtime rather than silently loading nothing."
            );
            return;
        }
    };

    if !vmlinux_h.exists() {
        println!(
            "cargo:warning=aivisor-bpf: src/bpf/vmlinux.h not found — generate it with \
             `bpftool btf dump file /sys/kernel/btf/vmlinux format c > src/bpf/vmlinux.h` \
             against the kernel these programs will run on. BPF programs will not be built."
        );
        return;
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));

    for name in OBJECTS {
        let src = bpf_src_dir.join(format!("{name}.bpf.c"));
        let dst = out_dir.join(format!("{name}.bpf.o"));
        compile_one(&clang, &src, &dst, &bpf_src_dir);
    }

    println!("cargo:rustc-env=AIVISOR_BPF_OUT_DIR={}", out_dir.display());
}

fn find_clang() -> Option<PathBuf> {
    let candidate = env::var("CLANG").unwrap_or_else(|_| "clang".to_string());
    let ok = Command::new(&candidate)
        .arg("--print-targets")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if ok {
        Some(PathBuf::from(candidate))
    } else {
        None
    }
}

fn target_arch_define() -> &'static str {
    // libbpf CO-RE convention (see libbpf-bootstrap): vmlinux.h's
    // arch-conditional sections key off __TARGET_ARCH_<name>, which the
    // kernel's own headers don't set for us when cross-compiling BPF
    // bytecode (the -target bpf backend has no "arch" of its own).
    match env::var("CARGO_CFG_TARGET_ARCH").as_deref() {
        Ok("x86_64") => "__TARGET_ARCH_x86",
        Ok("aarch64") => "__TARGET_ARCH_arm64",
        Ok(other) => panic!(
            "aivisor-bpf: no __TARGET_ARCH_* mapping for target_arch={other} — \
             blueprint.md's supported kernel matrix is x86_64/aarch64 only"
        ),
        Err(_) => "__TARGET_ARCH_x86",
    }
}

fn compile_one(clang: &Path, src: &Path, dst: &Path, include_dir: &Path) {
    let arch_define = format!("-D{}", target_arch_define());
    // -g + BTF preserves debuginfo the verifier's CO-RE relocation step
    // needs; -O2 is required for BPF (unoptimized BPF code very often
    // fails to verify — this is a well-known, not-optional constraint of
    // the BPF backend, not a normal optimization preference).
    let status = Command::new(clang)
        .args([
            "-target",
            "bpf",
            arch_define.as_str(),
            "-g",
            "-O2",
            "-Wall",
            "-Wno-unused-value",
            "-Wno-pointer-sign",
            "-Wno-compare-distinct-pointer-types",
            "-c",
        ])
        .arg("-I")
        .arg(include_dir)
        .arg(src)
        .arg("-o")
        .arg(dst)
        .status()
        .unwrap_or_else(|e| panic!("failed to invoke clang for {}: {e}", src.display()));

    if !status.success() {
        panic!(
            "clang failed compiling {} (exit: {status}) — this is a real BPF C compile error, \
             not a missing-toolchain issue; fix the source rather than the build script",
            src.display()
        );
    }
}
