[package]
name = "aivisor-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rustix = { workspace = true, features = ["fs"] }
thiserror = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
camino = { workspace = true }
tracing = { workspace = true }
